### ISSUE TITLE
Link to github project wrong

### ISSUE THREAD

**Issue by dploeger** [tangram-js/json-schema-editor#4]
There's an error in your website where the first link to the github project leads to https://github.com/idjhuang/json-schema-editor

This and the note about Json Editor being a successor of Json Schema Editor lead me to believe, that Json Schema Editor is discontinued.

Perhaps you could clarify this.

**Comment by idjhuang** [comment]
Thank you for point out the issue, the correct link should be [https://github.com/tangram-js/json-schema-editor](https://github.com/tangram-js/json-schema-editor).
About the JSON Editor, it's the successor of JSON Schema Editor, which could edit general JSON with schema support: guide to add valid JSON element and validate the JSON document.
Because the JSON schema itself is a JSON document, so JSON Editor could also edit JSON schema with build-in meta-schema of JSON schema.
The original JSON Schema Editor project would be maintenance only, no feature upate.

**Comment by tangram-js** [comment]
Thank you for point out the issue, the correct link should be https://github.com/tangram-js/json-schema-editor.
About the JSON Editor, it's the successor of JSON Schema Editor, which could edit general JSON with schema support: guide to add valid JSON element and validate the JSON document.
Because the JSON schema itself is a JSON document, so JSON Editor could also edit JSON schema with build-in meta-schema of JSON schema.
The original JSON Schema Editor project would be maintenance only, no feature upate.
